### PR TITLE
Added distance counter.

### PR DESCRIPTION
**Pull request by antoniomdk**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Can you resolve the merge conflicts?

**Comment by antoniomdk** [comment]
That are dw same commits that were merged before. The last one is tje only that is needed to be merged

**Comment by niccokunzmann** [comment]
can you check out the new branch and use the cherry-pick command and crate a new pull request?

**Comment by antoniomdk** [comment]
I am going to have a look to it.

**Comment by niccokunzmann** [comment]
@antoniomdk There is also the offical Fossasia Account on the Play Store. Would you like it more if we hosted the app on this account? Or, in future, if somebody modifies the app, would you upload it again?

**Comment by niccokunzmann** [comment]
References issue #45

**Comment by antoniomdk** [comment]
Sorry, I have been out. Yes, you can upload it to Fossasia account, no problem. I was trying to solve the branch conflict but I can't.

**Comment by niccokunzmann** [comment]
Which are the important commits?

**Comment by niccokunzmann** [comment]
@antoniomdk I am closing this for now. You can reopen it if you like.

**Pull request closed without merging**
