### PR TITLE
Modified the index page with a navigation bar and background 

### PR DESCRIPTION
**Pull request by hemanthsavasere**

### CODE REVIEW

**Comment by hemanthsavasere** [comment]
thanks @niccokunzmann 
Can I do this for other pages too,  like the contributors page and the leaderboard page.

**Comment by niccokunzmann** [comment]
@hemanthsavasere Thanks, yes, if you like, you can do this.

**Comment by niccokunzmann** [comment]
I like that everything is loaded form the site.

**Comment by niccokunzmann** [comment]
By the way: If you like, you can create issues for small improvements that you could fix but that are really easy. This way, we can give them to beginners and you can help them. This is also a task on GCI, to help (beginners) resolve an issue.

**Pull request merged**
