### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by niksj**
Created a new character (butterfly)

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, if you would like to add this character so one can play it, you need to create a new layer in flappy.svg and also adapt the code. If you just would like to add the image, you should add it to the images folder.

**Comment by niksj** [comment]
I created a layer.But flappy.svg is a very huge file, i think i messed up something...

**Comment by niccokunzmann** [comment]
@niksj How can I tell if you messed up?

**Comment by niksj** [comment]
I checked it properly and now its absolutely perfect. I added changes and created a different pull request for it: #110 .

**Pull request closed without merging**
