### PR TITLE
New pages

### PR DESCRIPTION
**Pull request by Marauderer97**
Added pages about.html and download.html with some basic styling, issue #195  @niccokunzmann  I wasn't sure what else the about page should contain.. any suggestions are welcome :P :)

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
@Marauderer97 nice work can you squash the commits please

**Comment by Marauderer97** [comment]
image
image
This is how the pages look..

**Comment by Abhi2424shek** [comment]
@Marauderer97 good work! Can you add the other links as well to the downloads page [see the master branch's readme for links!]

**Comment by Marauderer97** [comment]
@Abhi2424shek Something went wrong as I tried to squash the commits, can you merge this for now, I will squash them from the next PR . Thanks!

**Comment by Marauderer97** [comment]
@Abhi2424shek I'm sorry I don't get you, I have added all the links from the READ ME page, which ones are you referring to?

**Comment by niccokunzmann** [comment]
@Marauderer97 Thanks!
@Abhi2424shek let`'s merge fast and create issues.

**Pull request merged**
