### PR TITLE
Added 2 new characters and few sound effects

### PR DESCRIPTION
**Pull request by yvars**
Added 2 new characters (Blocky the pig and a ball).
Also added a flap sound effect and a game over sound effect.
Now the game shows a alert window when you lose.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
There are some merge conflicts. Can you resolve them? It might be easier to use the current file and add your own characters again but it could also be possible to search for `>>>>>>`   `=======` and `<<<<<<`

**Comment by niccokunzmann** [comment]
Thanks for this, I would really like to merge it :)

**Comment by yvars** [comment]
OK. The changes were small so I have no problem in redoing them 😄

**Comment by niccokunzmann** [comment]
A change of flappy.svg happened.

**Comment by niccokunzmann** [comment]
@yvars You can close this if it is not needed any more.

**Comment by yvars** [comment]
Alright closed @niccokunzmann!

**Pull request closed without merging**
