### PR TITLE
Added Octodex Character

### PR DESCRIPTION
**Pull request by Elgayar**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks, can you check if everything works on the website?

**Comment by Elgayar** [comment]
It's not, any hints on what is my problem? @niccokunzmann

**Comment by niccokunzmann** [comment]
Yes, please describe (1) what you expect to see (2) describe what you see instead (3) describe additional hints.

You can also open an issue.
Keep in mind that you may need to refresh with control+r

**Comment by Elgayar** [comment]
I expect to see my character available to pick. Instead, my character doesn't appear... However there are no errors..

**Comment by niccokunzmann** [comment]
You can create this as an issue.

**Pull request merged**
