### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by ApurvJain123**

### CODE REVIEW

**Comment by jig08** [comment]
@niccokunzmann Are you seeing after this PR ? Too many commits and conflicts.

**Comment by niccokunzmann** [comment]
@ApurvJain123 It is possible but ot desirable to merge gh-pages into master or vice-versa.

**Comment by niccokunzmann** [comment]
gh-pages is only the small website for download. master is all the rest - documentation, apps, ...

**Comment by niccokunzmann** [comment]
But :) you successfully create a pull-request. If you have a commit which you like to use in the gh-pages or master branch, you can use `git cherry-pick`.

**Comment by niccokunzmann** [comment]
Please ask, if you like to know more.

**Pull request closed without merging**
