### PR TITLE
Updated Binary and Source of Windows Flappy SVG

### PR DESCRIPTION
**Pull request by adarsh-ideal**
#### V 2.0
 - Updated source
 - Used LZMA compression for small binary size
 - Fixed few bugs

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks. I do not know, what you updated the mode of so many files for.

**Comment by adarsh-ideal** [comment]
I updated source, "content" folder with gh-pages branch.
And compiled new installer with updated game.

**Comment by adarsh-ideal** [comment]
Also minimalized installer, it was around 40 mb then but now it is around 23-25 mb.

**Comment by adarsh-ideal** [comment]
I didn't changed the mode, it was automatically changed by git when I pushed it to my fork.

**Comment by niccokunzmann** [comment]
okay. Have you seen the new automatic build issue? What do you think? Do you know, what the console build command looks like?

**Comment by niccokunzmann** [comment]
https://github.com/fossasia/flappy-svg/issues/250

**Comment by adarsh-ideal** [comment]
Its for android.

**Comment by adarsh-ideal** [comment]
I can try to make it work.

**Comment by niccokunzmann** [comment]
Uh - we can also work on a windows build - there is AppVeyor - a Windows travis so to say.

**Comment by adarsh-ideal** [comment]
Yeah, I checked that.
Compiling the installer is easy and can be performed from command line, we just need the .nsi script
But I need time to find an application to generate the .nsi script through command line on each new commit.

**Pull request merged**
