### PR TITLE
Fixed an issue with the new layer

### PR DESCRIPTION
**Pull request by manastaneja**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, I would like to merge it but somebody already edited the file. Are you able to make the changes, so it can be merged?

**Comment by Abhi2424shek** [comment]
@manastaneja pls resolve the conflicts bro please update and resolve the conflicts we can assist you if you are not able to resolve the conflicts we can't resolve them as github states it's too complex to fix.

**Comment by manastaneja** [comment]
@Abhi2424shek Please check your mails. I have some queries :)

**Comment by Abhi2424shek** [comment]
Yikes my mail? @manastaneja pls wait.... next time pls don't mail just ping on slack.

**Comment by Abhi2424shek** [comment]
As you requested closing this...

**Pull request closed without merging**
