### PR TITLE
added a loading animation

### PR DESCRIPTION
**Pull request by hemanthsavasere**
image

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi, great! @fossasia/gci16-maintainers Can someone merge?

@hemanthsavasere, We need download the jquery file and put it into the JavaScript folder somewhere.

1. Google tracks users of the game
2. It will not work offline or in the [apps](https://github.com/fossasia/flappy-svg/tree/master#flappy-svg-) on the go

**Comment by m1guelpf** [comment]
@niccokunzmann The mantainers team only hash push access to the gci16 website repo.

**Comment by niccokunzmann** [comment]
@m1guelpf, does the GUI allow a merge for you? merge=pull+merge+push

**Comment by m1guelpf** [comment]
@niccokunzmann It says I need write acces to the repo to merge

**Comment by hemanthsavasere** [comment]
Hi, @niccokunzmann 
 I'll tweak it a little it.

thanks

**Comment by Abhi2424shek** [comment]
@niccokunzmann sorry, I was away. Merged it. Good work @hemanthsavasere

**Comment by hemanthsavasere** [comment]
thanks @Abhi2424shek

**Pull request merged**
