### PR TITLE
Adding character botty

### PR DESCRIPTION
**Pull request by rhemon**
Added a character called botty.

Task: https://codein.withgoogle.com/dashboard/task-instances/4945314031075328/

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Hi rhemon. Can you play the game and check? I could not see your character when I clicked on the others. It is a list where each character has its onclick, I believe.

**Comment by rhemon** [comment]
no it does show up. 
screen shot 2016-12-12 at 12 51 10 pm
screen shot 2016-12-12 at 12 51 16 pm

**Comment by niccokunzmann** [comment]
Okay, I forgot to refresh.

**Comment by niccokunzmann** [comment]
And I accepted the task. Feel free to program more, if you like :)

**Comment by rhemon** [comment]
thanks, gonna work on adding a background now, its actually really fun (although i am very bad at drawing)

**Pull request merged**
