### PR TITLE
ICO file added to index.html

### PR DESCRIPTION
**Pull request by anniezhou301**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
This should close #10

**Comment by jig08** [comment]
@niccokunzmann 
We could maybe keep #10 open for varied ideas ? Or shall we close it ?

**Comment by niccokunzmann** [comment]
@jig08 I closed it because the problem is solved. If there are other, even similar ideas, we can open a new issue. Leaving it open just clutters the issues and nobody wants to read it any more. - My opinion. You can go ahead and create other issues.

**Comment by jig08** [comment]
@niccokunzmann As you say :) No qualms.

**Pull request merged**
