### PR TITLE
fixed black_cat bug

### PR DESCRIPTION
**Pull request by hemanthsavasere**
Fixed the black cat bug and now it is working.

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
Can you give a preview like that to your gh-pages or a screenshot, that would help a lot

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
@Abhi2424shek, here it is super important to review fast. If there are two pull-requests for the flappy.svg file, chances are, one of them needs to redo the work. By merging fast, we can minimize this risk.

**Comment by Abhi2424shek** [comment]
Ok that's cool i understand sir

**Comment by hemanthsavasere** [comment]
fine 
image
image
image

**Pull request merged**
