### PR TITLE
Added new character "bat", added support for changing character

### PR DESCRIPTION
**Pull request by PohSayKeong**
Sequence: Bird,Bat

onclick="changeCharacter'Character to change into'"

   if (layer == 'character to change into'){
	layerNamed('character to change into').style.display = 'inline';
	layerNamed('current character').style.display = 'none';
	flappy = new Flappy(layer)}

### CODE REVIEW

**Comment by sudheesh001** [comment]
@PohSayKeong the character change to a bat is only working for a few times after which it stops to change characters can you look into that ?

**Comment by PohSayKeong** [comment]
@sudheesh001 That is not the case for me, anyway I can replicate the bug?

**Comment by sudheesh001** [comment]
I have a new problem now, both of them are on the screen.
screen shot 2015-12-21 at 10 13 26 am

Before starting the game, click on the camel to turn it into a bat and then click play.

**Comment by PohSayKeong** [comment]
Yeah, I just realized, it only changes before the game starts. I will look into that

**Comment by PohSayKeong** [comment]
The problem with this is that the code says startFlapping is 'bird', so it will always be bird. So I would want startFlapping to store a variable instead, but it seems that I am unable to that.

var character = layerNamed('bird')
function startGame() {
    // this must be configured one mousedown event in the start screen
    layerNamed('startscreen').style.display = 'none'; // none = hide layer
    startFlapping(character);
    startMovingBackgound('background', -7);
    startMovingBackgound('cactus', -7);
    startMovingBackgound('DayAndNight', -20);
    startMovingBackgound('SunAndMoon', 1);
    scaleToFullscreen();
}

function changeCharacterBird(){
	layerNamed('bird').style.display = 'none'
	layerNamed('bat').style.display = 'inline'
	var character = layerNamed('bird')
}

function changeCharacterBat(){
	layerNamed('bat').style.display = 'none'
	layerNamed('bird').style.display = 'inline'
	var character = layerNamed('bat')
}

I will get layer 'bird' is not found

**Comment by sudheesh001** [comment]
Can you point out what the `startFlapping()` function is doing ?

**Comment by PohSayKeong** [comment]
function startFlapping(Layer) {
    if (!flappy) {
        flappy = new Flappy(Layer);
    }
    flappy.startFlapping();
}

startFlapping has a layer as parameter

**Comment by sudheesh001** [comment]
Can you disable the layer being clickable until and unless the "play" button has been clicked ?

**Comment by PohSayKeong** [comment]
But if the layer is not clickable, the character wont be able to change. If play is clicked and then the layer becomes clickable, wouldn't players need to change their character in game?

**Comment by sudheesh001** [comment]
Yes the players should be allowed to make the change of character but do not allow them to do that unless the game has started with the play button, you could have a global variable called `playBit` or something which checks if the play button has been pressed or not, depending on the value, the operations like click to change character should be allowed.

**Comment by PohSayKeong** [comment]
Then what do players click to actually start the game?

**Comment by sudheesh001** [comment]
the players click the `start/play` button and once the game starts, they can click the character

**Comment by PohSayKeong** [comment]
So they will be changing their character while the game is running behind?

**Comment by sudheesh001** [comment]
Yup sure, I think that sounds good. It changes once the user clicks on the character right ?

**Comment by PohSayKeong** [comment]
It starts to get a little complicated from here, because once the game starts the flappy locks on to the initial character, so I need to create another function that allows them to change the character with onclick. I will see what I can do and come back to you later.

**Comment by sudheesh001** [comment]
Great, I am sure you can do it @PohSayKeong

**Comment by PohSayKeong** [comment]
Thanks for the help just now, I was able to allow players to change their character on the main screen before the game starts by clicking on it, everything works fine after that. I also added a function to disable the function to change character during game so that players don't accidentally change their character.

**Comment by niccokunzmann** [comment]
Wow! Wonderful!

**Pull request merged**
