### PR TITLE
Added a built version of FlappySVG_Custom (apk)

### PR DESCRIPTION
**Pull request by yvars**

### CODE REVIEW

**Comment by yvars** [comment]
Here is the link to the Google Code In Task: https://codein.withgoogle.com/dashboard/task-instances/5884427622154240/
And link to my previous pull request: https://github.com/fossasia/flappy-svg/pull/146

**Comment by yvars** [comment]
That was quick! @niccokunzmann  should I now submit the task for review?

**Comment by niccokunzmann** [comment]
Yes, you can. I will look at the app and if it works, I accept.

**Comment by niccokunzmann** [comment]
Also, if you like: you can rename the file and put it into the folder.

**Comment by niccokunzmann** [comment]
First time, I could not play the game but second try it worked.  Thanks!

**Comment by yvars** [comment]
I will surely do it but for that I will have to create another pull request right?

**Comment by niccokunzmann** [comment]
yes

**Comment by niccokunzmann** [comment]
Did you add something to the game? it could be interesting for you to add it to the master branch, too.

**Comment by niccokunzmann** [comment]
Another idea: Can we automate the build of your app on the command line? If yes, we can create a new app every commit.

**Comment by yvars** [comment]
I added 2 new characters (the pig one and a ball) and I also added flap sound and game over sound. And a alert when you die. That's all I did. Should I upload that to the master branch too.
For the automation of app I haven't really done anything like that before but I would try and let you know. It would be really awesome if I am able to do that but I am not sure!

**Comment by yvars** [comment]
Thanks for accepting that task!

**Comment by niccokunzmann** [comment]
If we try it together, we should create an issue and talk there. Then, we can invite other mentors to also help us.
If you like to work on this, please create the issue and describe how you build the app. Then, we can see if we can use travis to also build the app.

**Comment by niccokunzmann** [comment]
Your new characters should be in the gh-pages branch, so other people can play them, too.

**Comment by niccokunzmann** [comment]
With the sounds it is a question: are they made by you and under which license are they? One can get in legal trouble in some countries if we do not conform to the sound license.

**Comment by yvars** [comment]
Alright I will create a issue asking for help for the automatic build. And will create another pull request for gh-pages (for characters) and master (moving the build to FlappySVG_Cusom) Folder.

I download the sounds form Freesound.org which has 3 licenses all are free for open source projects and I also credited the authors so I don't think there should be a problem with sounds.

**Comment by niccokunzmann** [comment]
Crediting the authors may not be enough, depending on the license. I think, we will need a LICENSE file in next to the sounds. Can you gibe me some links?

**Comment by yvars** [comment]
Alright. Here is the link to the first sound: https://www.freesound.org/people/makkuzu/sounds/234257/
Unfortunately I could not find the link to the second (flap sound). The developer must have removed it. But the link to the developer page: http://www.freesound.org/people/ani_music

**Pull request merged**
