### PR TITLE
Fix: howToPlay page will show up in chrome browser

### PR DESCRIPTION
**Pull request by tripti1410**
This PR addresses issue #274 

[http://flappy.fossasia.org/howtoplay.html](url) This was not visible in chrome browser

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@tripti1410 Thanks! Did you check it is visible in other browsers, still?

**Comment by TheClassicWizard** [comment]
Page is still not visible. Just a yellow Blank Screen!
Screenshot (2)

**Comment by tripti1410** [comment]
Which browse? I tested in latest version of chrome, Firefox and safari?

**Comment by TheClassicWizard** [comment]
Yeah, My Bad! It's in function well and good! Thanks for response to the query!

**Pull request merged**
