### PR TITLE
Possible fix for bug #273

### LINKED ISSUE #273: Game Over without touching any object?
Hello,
Was just trying this project for [Hacktoberfest 2019](https://hacktoberfest.digitalocean.com/details) and while searching throughout one of the README files, there was a link to http://flappy.fossasia.org/ where it was possible to test the game. I'm not sure if that's just a test URL where the game is not supposed to work at all or not. But I was constantly getting Game Over without hitting any objects.
In attachment follows a screen shoot to illustrate this.

flappy fossasia org - wrong game over state

### PR DESCRIPTION
**Pull request by unsuitable001**
Possible fix for bug #273
Fixes #273

### CODE REVIEW

**Comment by unsuitable001** [comment]
Travis is failing due to broken play store link. Ref #289

**Comment by niccokunzmann** [comment]
This does not fix the build. What do you propose as a next step?

**Comment by unsuitable001** [comment]
> This does not fix the build. What do you propose as a next step?

Maybe a better collision detection.

Can I ask you one thing? As the `js` is inside embed, how can I `console.log` or, manipulate values or run functions from `browser console` ?

**Comment by niccokunzmann** [comment]
To open the console, you should be able to run the svg file directly in
the browser.

**Comment by unsuitable001** [comment]
On it. I'll push commit ASAP.

**Pull request closed without merging**
