### PR TITLE
Added new background and character.

### PR DESCRIPTION
**Pull request by Baidya99**
Task: https://codein.withgoogle.com/dashboard/task-instances/5812223081447424/

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I am merging this first, so others can build on your work.

**Comment by niccokunzmann** [comment]
Please play the game and write down issues to solve.

**Comment by niccokunzmann** [comment]
Thanks for adding a new character and background.

**Comment by Baidya99** [comment]
Even after adding scripts in the links the background is not acting as it should. Can you tell me why?

**Pull request merged**
