### PR TITLE
An about page with essential links Issue #29

### PR DESCRIPTION
**Pull request by alan-aipe**
An about page has been linked with home page of game and the about page contains links to fossasia website, github link, android apk and play store links,link to rotoscopes and a link back to game

### CODE REVIEW

**Comment by alan-aipe** [comment]
I have added the sun back.. but what is octo-arm?
@niccokunzmann

**Comment by niccokunzmann** [comment]
The octo-arm is the github octocat in the top right corner. We have a css file just for its style. If this file is no longer needed, it can be removed. https://github.com/fossasia/flappy-svg/blob/gh-pages/index.css

**Comment by alan-aipe** [comment]
ok.. done... @niccokunzmann

**Comment by niccokunzmann** [comment]
@alan-aipe Thanks for adding all this. It looks really sophisticated. If you wish, you can add your name to the contributors file in the master branch.

**Comment by alan-aipe** [comment]
Thank you @niccokunzmann .. I have opened a pull request to add myself to contributors list - #59 . Thank you for your feedbacks as well

**Pull request merged**
