### PR TITLE
Added a new character, background and obstacle

### PR DESCRIPTION
**Pull request by adarsh-ideal**
Added new background 'Island',
new character 'unicorn'
and new obstacle 'thunder'

### CODE REVIEW

**Comment by adarsh-ideal** [comment]
Task:
https://codein.withgoogle.com/dashboard/task-instances/4899907368386560/

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
Can you play the game, switch through all characters and backgrounds and try your background?
If you encounter any issues, please open issues for them.

**Comment by adarsh-ideal** [comment]
There are many backgrounds in the game but can switch between only three of them ( There are only three available in menu ).
There is an issue Choose Space Background by Click https://github.com/fossasia/flappy-svg/issues/131.
But we will have to add all the backgrounds in the background selection menu and I think this will make the start screen more messier.

**Comment by adarsh-ideal** [comment]
I just saw that the svg file is splitted into several parts and it's more managed than before. 
We can change the javascripts to work with the changes made and while doing this we can solve this issue too.

**Comment by niccokunzmann** [comment]
This is an issue #108

**Comment by niccokunzmann** [comment]
Please comment there if you like to help.

**Comment by adarsh-ideal** [comment]
Yeah Sure!

**Pull request merged**
