### PR TITLE
Add animat

### PR DESCRIPTION
**Pull request by hwilson2563**
Address #22 

This animation makes the rocket look as though it is blasting through the course.

### CODE REVIEW

**Comment by hwilson2563** [comment]
@niccokunzmann I am unsure why this is failing since I only changed two files, one only related to the actual animation. Is there anything else I need to do to clean this Travis-ci error?

**Comment by hwilson2563** [comment]
looks like some of the links in the credits are 404 :( but I don't think I should be the one to remove these, what do I do? @niccokunzmann

**Comment by hwilson2563** [comment]
I have commented out the broken links, please let me know if you want these removed completely.

**Comment by niccokunzmann** [comment]
All fine!  Thanks!

**Review by JuniorPress — COMMENTED** [review]
credits.html

**Pull request merged**
