### PR TITLE
Added character, obstacles and background

### PR DESCRIPTION
**Pull request by BohJieQi**

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Could you please state which bugs you fix?

**Comment by niccokunzmann** [comment]
It is important to have a proper message. I merged this, because you change the svg file which is important to merge fast. Please, what is it you improved?

**Comment by BohJieQi** [comment]
Sorry! I fixed an error which caused the characters to be unable to hop

**Comment by BohJieQi** [comment]
I submitted the task for obstacles

**Pull request merged**
