### PR TITLE
Link fix

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixed the link to the instructions page, as mentioned in issue #225

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks for the two pull-requests. I see you contribute a lot, would you like to become a maintainer? This means merging pull-requests from other people. Your own pull-requests will be merged by others, still.

**Comment by niccokunzmann** [comment]
Here is a document about maintaining: https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/maintainers.md

**Comment by niccokunzmann** [comment]
If you do not want to be a maintainer, you can just go on like you did before :)

**Comment by Marauderer97** [comment]
@niccokunzmann Yes, I think being a maintainer will be fun :).

**Pull request merged**
