### PR TITLE
Added offline support(Android App)

### PR DESCRIPTION
**Pull request by antoniomdk**
I have added support for offline playing. I copied the web project into an asset folder, so the app when starts checks if there internet connection, and if not, use the local website.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I will not accept this: It creates duplicated files.

As I stated in #25 you should download the files automatically. and serve them locally. You already did 1/3 of the task: serving them from the local copy. Have a look at how to download the zip file and how to extract files from zip files in Java.

**Comment by antoniomdk** [comment]
Ok, no problem, I am trying to coding a downloader manager to download and unzip files.

**Comment by antoniomdk** [comment]
Sorry,  I have a problem. When the program starts to unzip,  the garbage collector starts to run and it blocks the app. The app downloads well but the problem is the second part. Could you help me or give me some tip? Thanks.

**Comment by niccokunzmann** [comment]
Where can I find the code?

**Comment by antoniomdk** [comment]
Sorry, I solved it. I used 3 util classes, I am going to upload the project.

**Comment by niccokunzmann** [comment]
I commented on the commit. It looks ok. Can you add the .apk file? 

Note: Usually the previous commits that add the flappy files and remove them would not be included. If you like to remove this, you are welcome. But I will will merge it as soon as

- you remove the code duplication
- you provide the apk file
- I tested the app

**Comment by antoniomdk** [comment]
Perfect, I'm on it.

**Comment by antoniomdk** [comment]
I do not know how to remove commits.

**Comment by niccokunzmann** [comment]
No Problem. It is optional.

I can not reproduce the app being able to run offline.
I think that you store the file contents on the USB/SD-card. 
I had a small search and found [this](https://developer.android.com/guide/topics/data/data-storage.html#filesInternal).

**Comment by antoniomdk** [comment]
Yes, I use external storage, I am going to try to use internal storage, thanks you for the link.

**Comment by antoniomdk** [comment]
I have tried to use app directory, it do not works, I tried to use a lib, it do not works. Finally I deleted every change I had made and I used the Cache directoy. It works for me, but I could not check in other device.

**Comment by niccokunzmann** [comment]
Can you again, provide the apk?

**Comment by antoniomdk** [comment]
Oh, sorry I forgot it. sorry

**Comment by antoniomdk** [comment]
It is uploaded.

**Comment by niccokunzmann** [comment]
The first test worked: Restart the app and turn off WIFI. The second test also worked: restarted tablet :+1: This is really awesome!

**Comment by niccokunzmann** [comment]
What are your wishes on how to go on with the development of this app?

**Comment by antoniomdk** [comment]
I think there more issue that we need to solve. I will select an issue and go on it. I also thought that I can try to use Intel XDK to create apps for other systems.

**Pull request merged**
