### PR TITLE
Added new background layer.

### PR DESCRIPTION
**Pull request by Antrismus**
Added new space background. And two layer rocket(player) and space_rocket(obstacle).

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I will merge it, so others can build on top of your work but there are some small things which still need fixing.

**Comment by niccokunzmann** [comment]
I added three issues and I will help you solve them. What do you think?

**Comment by Antrismus** [comment]
Ok, great!)))))

**Comment by niccokunzmann** [comment]
Task: https://codein.withgoogle.com/dashboard/task-instances/5187116361318400/

**Comment by niccokunzmann** [comment]
@Antrismus Can you post a like to your task instances, too? So we can skip back and forth between them? This helps us mentors. I am not sure if I use the correct link. Is it https://codein.withgoogle.com/dashboard/task-instances/5187116361318400/ ?

**Comment by Antrismus** [comment]
Yes, this is correct link. I don't understand what should I post?

**Comment by niccokunzmann** [comment]
We just need to document back and forth where something happened, so all mentors can follow easily.

**Comment by Antrismus** [comment]
Ok, I've got it. Starting working on your issues.

**Pull request merged**
