### PR TITLE
Added Custom Android App

### PR DESCRIPTION
**Pull request by yvars**
The game is included in the app and do not need to be downloaded. Also
added Sound Effects and 2 new characters

### CODE REVIEW

**Comment by niccokunzmann** [comment]
I am merging and opening some issues on ideas what can be improved.

**Comment by niccokunzmann** [comment]
Thanks, if I would like to try it out, is there something you have?

**Comment by yvars** [comment]
Here is the link to the Google-Code-In task @niccokunzmann https://codein.withgoogle.com/dashboard/task-instances/5884427622154240/

**Comment by yvars** [comment]
@niccokunzmann I did not understood what you meant by "if I would like to try it out, is there something you have?". Do you mean you want an built apk? In that case should I open another request with a built version?

**Comment by yvars** [comment]
If you really want to try it out fast, you can download it form here: https://github.com/yvars/flappy-svg/blob/master/FlappySVG_Cusom.apk
Should I open a pull request again to include the apk in the master branch?

**Comment by niccokunzmann** [comment]
Yes, please open a pull-request.

**Comment by yvars** [comment]
@niccokunzmann  here is the link: https://github.com/fossasia/flappy-svg/pull/152 (to the new pull request)

**Pull request merged**
