### PR TITLE
Added score again

### LINKED ISSUE #194: Score button is not showing.
Somewhere the score button is not visible any more.

### PR DESCRIPTION
**Pull request by Baidya99**
Resolves #194

Also
-Changed the look of Game Over.
-Added link to help file
-Renamed the obstacle layer 'obstacle' to energy and added a background for it and also the required code.

New
Original

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@Baidya99 Thanks! Can you inform the person who created the obstacle layer about the background?

**Comment by Baidya99** [comment]
Okay but how?

**Comment by Baidya99** [comment]
Could you please approve my task: https://codein.withgoogle.com/dashboard/task-instances/5126539890917376/

**Comment by niccokunzmann** [comment]
Approved :)

**Comment by reallyly** [comment]
I saw your background! Nice work, I like it!

**Pull request merged**
