### PR TITLE
Added New Obstacles

### PR DESCRIPTION
**Pull request by reallyly**
I edited the `flappy.svg` file  add a new obstacle layer named "obstacle".

### CODE REVIEW

**Comment by daminisatya** [comment]
@niccokunzmann Please a have look :D

**Comment by Baidya99** [comment]
Have you also added a background for your obstacle layer as they go in pairs.
Also add the necessary code to the javascript files for them to work.
For help on adding javascript see this PR #129

**Comment by niccokunzmann** [comment]
Thanks for your contribution!

**Comment by reallyly** [comment]
@Baidya99, so, I have to make a background too?

**Comment by niccokunzmann** [comment]
You do not have to. But: The backgrounds and obstacles go together and are activated at the same time. So, you can create a new, empty background or re-use one of the existing ones. As you like.

**Comment by niccokunzmann** [comment]
Task: https://codein.withgoogle.com/dashboard/task-instances/6589571577937920/

**Comment by reallyly** [comment]
@niccokunzmann  Okay. I think I'd be happy to try to make a background that match with the obstacles I made, just for fun :).  Should  I draw one and make another pull request then?

I don't know how to code the JS script though.

**Comment by niccokunzmann** [comment]
Hi @reallyly please have a look at the current state of the game @Baidya99 added a background. Could be that everything is to your satisfaction.

**Comment by reallyly** [comment]
Oh, I saw that! Nice job @Baidya99! Anyway, I don't think the outline in my obstacles drawing matches @Baidya99 's background style, so, can I remove the outline and make a new pull request? @niccokunzmann

**Comment by niccokunzmann** [comment]
You can create new pull-requests, whenever you like to change the game.

**Comment by Baidya99** [comment]
@reallyly If you dont want to edit the js file you just delete my background and create your one naming it 'Evil'

**Comment by reallyly** [comment]
@Baidya99  I'm okay with your background.

**Pull request merged**
