### PR TITLE
Added app to the master branch.

### PR DESCRIPTION
**Pull request by Abhi2424shek**
Done as part of GCI task: https://codein.withgoogle.com/dashboard/task-instances/6293522636341248/

I created a new android app that will be using FlappySVG, here are the previews:
preview2
preview1

i added the source code via this PR.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks!

**Comment by niccokunzmann** [comment]
@Abhi2424shek For reviewing the task, can you provide me with a link to the apk? Also, you can add this link to the README.md file in the master branch.

**Comment by Abhi2424shek** [comment]
@niccokunzmann sure I will add it to the readme

**Comment by Abhi2424shek** [comment]
@niccokunzmann here's the link: https://drive.google.com/file/d/0Bwva5Kg_cjSIb2JEVnNMZ3lmems/view
I added a new PR as well adding it to the readme file.

Hope you'd review my task again, thanks
Happy coding :)

**Pull request merged**
