### PR TITLE
Errors

### PR DESCRIPTION
**Pull request by Marauderer97**
The PR solves the following problems:
1. linking dog through clicks
2. Making thunder hidden
3. Relocate ball character, to match other character's initial positions
4. Add separate svg files for ball and dog

### CODE REVIEW

**Comment by Abhi2424shek** [comment]
@jig08 nice to have you onboard but for squashing commits we have the squash and merge option so that won't be a problem ;)

**Comment by jig08** [comment]
I'd recommend no to use the `squash and merge` option for so many commits especially the merge ones. Thanks.

@Marauderer97 Could you pls do the needful ?

**Comment by Abhi2424shek** [comment]
Yikes you are on a separate branch can you try to give out some previews since it can be achieved locally pls give some screenshots @marauderer97

**Comment by Marauderer97** [comment]
Initially the ball was here:
image
Now it is here:
image

**Comment by Marauderer97** [comment]
Solves #242

**Comment by Marauderer97** [comment]
@Abhi2424shek @jig08 I used squash and merge while merging , so that all the commits are merged as one single commit, is this good?

**Comment by jig08** [comment]
@Marauderer97 

* I'd **seriously** recommend not to merge your own PRs especially if you have just recently started contributing to the project.
* Also, as mentioned before, I recommend not to use the `squash and merge` option for so many commits especially the merge ones.
* Plus the changes requested weren't done. The commit message wasn't renamed accordingly. 

Follow the guidelines to be a good contributor to any open source project and/or org.

**Comment by jig08** [comment]
@niccokunzmann Could you pls check who all have the write access to this project ? We'd like to have it limited to protect the sanity :)

**Comment by niccokunzmann** [comment]
@jig08 It is @Marauderer97 @Abhi2424shek and me. Yes, we should not merge our PR so fast and wait for at least a day but I think, they know it now and will follow this rule :)
They support the work flow as we need to merge fast here because flappy.svg can not be merged automatically but is changed almost every time.

@Marauderer97 squashing is good, sure.

**Comment by Marauderer97** [comment]
@jig08 My most sincere apologies
Firstly, I inferred from your conversation with @Abhi2424shek that you wanted me to squash and merge, and that is why i did it.
Secondly, I don't understand which commit message you are talking about? I thought you guys had asked for screenshots, and a related issue which this solves and I commented both of them..
Lastly, most of the things fixed were very minute errors, mostly in layers I had contributed myself, and simply involved creating new files or changing a single word, which is why I was so confident about the PR.
However point duly noted. Will be more careful next time. :)

**Comment by jig08** [comment]
@Marauderer97 

* Yes, The review required squashing the commits from your end using the terminal and not the web interface. Each PR should be matched with a single commit before we can merge into `master`.

* The [commit message](http://chris.beams.io/posts/git-commit/) needed to be changed to be more precise about the changes being done and keep a clean & lucid history, please read about git/github basics. It shall definitely help you improvise.

Thanks.

**Pull request merged**
